version: "3.9"
networks:
  simbirgo-dev:
    driver: bridge
services:
  app:
    container_name: simbirgo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - simbirgo-dev
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: firstdb
    ports:
      - "5432:5432"
    networks:
      - simbirgo-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: